In [1]:
# numpy >> numerical python
# 2005 by Travis oliphant
# numpy is stored in homogenous array

In [2]:
import numpy as np
np.__version__

'2.0.1'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
Mathemetics tool :- matlab, tora,lingo,spss

In [8]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)

numpy.ndarray

In [10]:
a = np.array([1,2,3,4,5,"pratap"])  # one string is convert to all string
a

array(['1', '2', '3', '4', '5', 'pratap'], dtype='<U21')

In [11]:
type(a)

numpy.ndarray

In [ ]:
# arr stores homogenous data

In [12]:
a.ndim

1

In [13]:
b = np.array([[1,2,3],[1,2,3]])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.ndim

2

In [16]:
# matrix is a specialised 2d array
np.matrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [17]:
np.matrix([[[1,2,3,4]]])

ValueError: matrix must be 2-dimensional

In [18]:
l = [1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [19]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [20]:
t = (1,2,3,True)
np.array(t)

array([1, 2, 3, 1])

In [22]:
d = {"Ram":500,"shyam": 300}
np.array(d)

array({'Ram': 500, 'shyam': 300}, dtype=object)

In [24]:
arr = np.fromfunction(lambda i,j: i==j, (3,3))

In [25]:
arr.ndim

2

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [ ]:
# make an array from tuple iterables

In [29]:
iterator = (i for i in range(5))
np.fromiter(iterator,int)

array([0, 1, 2, 3, 4])

In [30]:
arr.reshape(4, -100)

ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [31]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))
arr1@arr2

array([[ 8,  5,  7],
       [10,  6,  8],
       [ 6,  4,  6]], dtype=int32)

In [33]:
np.dot(arr1,arr2)

array([[ 8,  5,  7],
       [10,  6,  8],
       [ 6,  4,  6]], dtype=int32)

In [34]:
arr.T # transpose

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
arr1.flatten()

array([2, 2, 1, 2, 2, 2, 1, 2, 1], dtype=int32)

In [36]:
# expand dimension
np.expand_dims(arr1, axis = 0)

array([[[2, 2, 1],
        [2, 2, 2],
        [1, 2, 1]]], dtype=int32)

In [39]:
a = np.expand_dims(arr1, axis = 1)
a

array([[[2, 2, 1]],

       [[2, 2, 2]],

       [[1, 2, 1]]], dtype=int32)

In [40]:
a = np.expand_dims(arr1, axis = 1)

In [41]:
np.squeeze(a)

array([[2, 2, 1],
       [2, 2, 2],
       [1, 2, 1]], dtype=int32)

In [42]:
np.repeat(b, 2, axis = 1)

array([[1, 1, 2, 2, 3, 3],
       [1, 1, 2, 2, 3, 3]])

In [43]:
a = np.array([[1],[2],[3]])

In [44]:
a

array([[1],
       [2],
       [3]])

In [45]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [46]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [47]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.90929743, 0.90929743],
       [0.84147098, 0.84147098, 0.90929743]])

In [48]:
np.cos(arr1)

array([[-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684, -0.41614684, -0.41614684],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [49]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.30103]])

In [50]:
np.tan(arr1)

array([[-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986, -2.18503986, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [51]:
np.cot(arr1)

AttributeError: module 'numpy' has no attribute 'cot'

In [52]:
np.sort(a)

array([[1],
       [2],
       [3]])

In [53]:
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [54]:
b = np.array([16,3,0])

In [55]:
np.linalg.inv(arr1)

array([[ 1. , -0.5,  0. ],
       [-1. ,  1.5, -1. ],
       [ 0. , -0.5,  1. ]])

In [56]:
np.linalg.det(arr1)

np.float64(2.0)

In [57]:
p = np.random.rand(8,8)
print(p)

[[0.77914724 0.77769466 0.21041483 0.13676874 0.53785269 0.91787974
  0.06909165 0.32249603]
 [0.28496007 0.88148637 0.70148992 0.94516448 0.82416643 0.16166866
  0.71948375 0.13691645]
 [0.75527581 0.18960931 0.50736152 0.37714643 0.04606769 0.46262567
  0.90956712 0.0394123 ]
 [0.06048714 0.56133632 0.90892587 0.9443176  0.73124892 0.89477331
  0.75997869 0.08824302]
 [0.29715672 0.38135739 0.50965338 0.07596112 0.81684595 0.17341127
  0.63801485 0.33419829]
 [0.6290352  0.1589025  0.55640971 0.98411556 0.32159746 0.49309876
  0.70160252 0.72994707]
 [0.47170586 0.17435549 0.77716212 0.08070159 0.74942015 0.73858136
  0.81687973 0.30084513]
 [0.4975467  0.13753493 0.44834901 0.76550539 0.57412608 0.85283641
  0.66701249 0.82496295]]


In [60]:
import numpy as np

N = 8
rand_vals = np.random.randint(1,101,size=N)

out = np.eye(N) *rand_vals

rand_vals = np.floor(np.random.rand(N) * 100) + 1

In [64]:
# create a 3cross3 numpy array with random integers between 1 and 100.then, interchange its rows and columns in python
import numpy as np

arr = np.random.randint(1,101,size=(3,3))
arr

array([[27,  5, 46],
       [39,  2, 81],
       [85, 63, 84]], dtype=int32)

In [66]:
transpose = np.transpose(arr)
transpose

array([[27, 39, 85],
       [ 5,  2, 63],
       [46, 81, 84]], dtype=int32)

In [67]:
# Generate a 1D numpy array with 10 elements.Reshape it into a 2cross5 array, then into a 5cross2 array.
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [69]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

b = np.array()