# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [9]:
import numpy as np
arr = np.random.randint(0,101,(3,3))

In [10]:
arr

array([[30,  5, 83],
       [97, 21, 24],
       [64, 40, 85]], dtype=int32)

In [11]:
arr.T

array([[30, 97, 64],
       [ 5, 21, 40],
       [83, 24, 85]], dtype=int32)

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [12]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [13]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [31]:
import numpy as np 
arr2 = np.random.rand(4,4)

In [32]:
arr2

array([[0.43135194, 0.11262903, 0.21142885, 0.30142146],
       [0.13783081, 0.04313855, 0.35115254, 0.20160814],
       [0.75340725, 0.93909213, 0.52101313, 0.56109233],
       [0.74880317, 0.53262065, 0.41458713, 0.81836698]])

In [39]:
arr3 = np.pad(arr2,pad_width=1, mode='constant',constant_values=0)

In [40]:
arr3

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.43135194, 0.11262903, 0.21142885, 0.30142146,
        0.        ],
       [0.        , 0.13783081, 0.04313855, 0.35115254, 0.20160814,
        0.        ],
       [0.        , 0.75340725, 0.93909213, 0.52101313, 0.56109233,
        0.        ],
       [0.        , 0.74880317, 0.53262065, 0.41458713, 0.81836698,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [60]:
import numpy as np
a1 = np.arange(10,65,5)

In [61]:
a1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

In [69]:
import numpy as np
a = np.array( ['python', 'numpy', 'pandas'])
print(f"Original Array:{a}")

# converting all characters to uppercase
upper_case = np.char.upper(a)  

# converting all characters to lercase
lower_case = np.char.lower(a)

# convertig the first character of each word in the string
title_case = np.char.title(a)

print("upper:",upper_case )
print("lower:",lower_case)
print("title:",title_case)

Original Array:['python' 'numpy' 'pandas']
upper: ['PYTHON' 'NUMPY' 'PANDAS']
lower: ['python' 'numpy' 'pandas']
title: ['Python' 'Numpy' 'Pandas']


# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [71]:
import numpy as np

arr = np.array(['python assignment','pandas','seaborn','numpy','plotly'])
print(f"Original Array:{arr}")

# using np.char.join to join elements of the array with a space character
r = np.char.join(" ",arr)

print(r)

Original Array:['python assignment' 'pandas' 'seaborn' 'numpy' 'plotly']
['p y t h o n   a s s i g n m e n t' 'p a n d a s' 's e a b o r n'
 'n u m p y' 'p l o t l y']


# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [108]:
import numpy as np
a2 = np.array([[1,2,3,4]])
a3 = np.array([[2,3,4,5]])
print("a2:",a2)
print("a3:",a3)

a = a2+a3
print("addition:",a)

b = a2-a3
print("substraction:",b)

c = a2*a3
print("multiplication:",c)

d= a2/a3
print("Division:",d)

a2: [[1 2 3 4]]
a3: [[2 3 4 5]]
addition: [[3 5 7 9]]
substraction: [[-1 -1 -1 -1]]
multiplication: [[ 2  6 12 20]]
Division: [[0.5        0.66666667 0.75       0.8       ]]


# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [114]:
import numpy as np
m = np.matrix([[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0],[0,0,0,0,1]])

In [115]:
m

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [128]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print(f"5x5 Identity Matrix:\n{identity_matrix}")

print(f"\nDiagonal Elements:\n{diagonal_elements}")


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers inthis array.

In [2]:
import numpy as np

# Create a random integers
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print(f"Original Array:\n{random_integers}")
print(f"\nPrime Numbers in the Array:\n{prime_numbers}")


Original Array:
[867 869 686 572 900 712 952 968 683 389 783 886 884 938 488 168 513 515
 641 987  14 111 581 522 324 787 802 974 126 910 275 870 570 213 805  72
 246 614 926 178 672 832   1 157 545 672 706 713 756 611 612 262 157 263
 644 579 195 883 994 379 474 867 556 429 494 989 485 856 574 444 344 875
 745 862 948 586 574 596 531 478 700  54 910 734 894 657 786 647  19 382
 181 412 650 985 256 340 159 913 763 679]

Prime Numbers in the Array:
[np.int32(683), np.int32(389), np.int32(641), np.int32(787), np.int32(157), np.int32(157), np.int32(263), np.int32(883), np.int32(379), np.int32(647), np.int32(19), np.int32(181)]


# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [33]:
import numpy as np

# create a numpy array with random daily temperatures for 30 days
daily_temperatures = np.random.randint(15,35,30)  # temparatures between 15 and 35 degrees

# Reshape the array into weeks (assuming 4 full weeks ad 2 extra days)
weeks = daily_temperatures[:28].reshape(4,7)

# calculate weekly averages
weekly_averages = np.mean(weeks,axis=1)

print("Daily Temperatures for the month:",daily_temperatures)
print("\nweekly_averages:",weekly_averages)

if len(daily_temperatures ) > 28:
    extra_days_average = np.mean(daily_temperatures[28:])
    print("\nAverage of extra days:",extra_days_average)

Daily Temperatures for the month: [27 31 16 19 30 16 33 16 28 28 16 18 26 15 33 15 25 19 20 17 23 17 24 24
 23 16 27 16 26 26]

weekly_averages: [24.57142857 21.         21.71428571 21.        ]

Average of extra days: 26.0
