In [1]:
import numpy as np

In [3]:
a = np.zeros(5) # Return a new array of given shape and type, filled with zeros.

In [4]:
a.ndim

1

In [5]:
a

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
b = np.zeros((3,4))

In [9]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
b.ndim

2

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int) # Return a new array of given shape and type, filled with ones.

array([1, 1, 1, 1, 1])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.twos(5) # doesn't exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [16]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [18]:
arr = np.zeros((3,4))

In [19]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
arr.ndim

2

In [21]:
# 3 dimensional array

np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr = np.zeros((3,3,4))

In [28]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
arr.ndim

3

In [30]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
b = np.zeros((1,1,3,3))

In [32]:
b

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [33]:
b.ndim

4

In [36]:
c = np.zeros((1,1,1,3,3))

In [37]:
c

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]])

In [38]:
c.ndim

5

In [40]:
arr = np.zeros((3,4))

In [41]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [43]:
a = arr + 5

In [44]:
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [45]:
a*2   # multiplication is indexwise

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [46]:
a - 1  # substraction is inedxwise

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [47]:
np.eye(3)  # Return a 2-D array with ones on the diagonal and zeros elsewhere. and identity matrics

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
np.empty((3,4)) # Return a new array of given shape and type, without initializing entries.It means entries in the array can be anything random values 

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [55]:
# optional >> random module
import random
random.choice((1,2,3,4,5))

5

In [56]:
random.choice("Ajay")

'A'

In [57]:
random.randrange(1,10)

3

In [58]:
random.random()  # a random number generated between 0(included) and 1 (excluded)

0.5033460009099465

In [59]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [61]:
random.shuffle(list)

In [62]:
list

[2, 4, 1, 5, 3]

In [63]:
random.uniform(7,14)

7.484603237222253

In [64]:
# random numbers related concept in numpy

np.array([])

array([], dtype=float64)

In [65]:
np.random.random_sample()

0.14769857861578262

In [66]:
np.random.random_sample((5, )) # 1 dim array of 5 random nos

array([0.56442457, 0.93774305, 0.7551036 , 0.40030352, 0.76110428])

In [67]:
np.random.rand(1)

array([0.69911943])

In [68]:
np.random.rand(2,3)

array([[0.17690873, 0.45163857, 0.87451062],
       [0.89574924, 0.72210659, 0.98021692]])

In [69]:
np.random.randn(2,3) # Return a sample (or samples) from the "standard normal" distribution.


array([[-0.37761464, -0.63176153, -1.32587439],
       [-0.37155436,  0.5124739 , -1.41398115]])

In [70]:
np.random.randint(1,5, size = (3,4)) # start from 1 and end at 5-1 and give array of shape 3,4

array([[4, 4, 1, 1],
       [1, 4, 1, 4],
       [3, 3, 3, 1]])

In [71]:
arr = np.random.randint(1,5, size = (3,4))

In [72]:
arr

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [73]:
arr.ndim

2

In [74]:
arr.shape

(3, 4)

In [75]:
arr.size

12

In [78]:
# reshaping of array
arr1 = arr.reshape(2,6) # Returns an array containing the same data with a new shape.

In [79]:
arr1

array([[3, 3, 1, 1, 1, 3],
       [2, 2, 4, 3, 3, 2]])

In [80]:
arr1.size

12

In [81]:
arr1.shape

(2, 6)

In [82]:
arr1.ndim

2

In [ ]:
# array size will never change,always reshape paramemeter should be multiplication of original size

In [83]:
arr

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [84]:
arr.reshape(3,2)

ValueError: cannot reshape array of size 12 into shape (3,2)

In [85]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [86]:
arr.reshape(3,4)

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [87]:
arr.reshape(4,3)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 4],
       [3, 3, 2]])

In [88]:
arr.reshape(1,12)

array([[3, 3, 1, 1, 1, 3, 2, 2, 4, 3, 3, 2]])

In [89]:
arr.reshape(12,1)

array([[3],
       [3],
       [1],
       [1],
       [1],
       [3],
       [2],
       [2],
       [4],
       [3],
       [3],
       [2]])

In [90]:
# case when you dont know in reshape what should be the row or column count
# use -any negative value for rows or columns
arr.reshape(4,-1)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 4],
       [3, 3, 2]])

In [92]:
arr.reshape(4,-100)

array([[3, 3, 1],
       [1, 1, 3],
       [2, 2, 4],
       [3, 3, 2]])

In [93]:
arr.reshape(-1,4)

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [94]:
arr

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [96]:
arr.reshape(12,1).base # to see the original array

array([[3, 3, 1, 1],
       [1, 3, 2, 2],
       [4, 3, 3, 2]])

In [98]:
arr.reshape(2,2,3) # multiplication should be equal to arr size

array([[[3, 3, 1],
        [1, 1, 3]],

       [[2, 2, 4],
        [3, 3, 2]]])

In [99]:
arr.reshape(1,2,2,3)

array([[[[3, 3, 1],
         [1, 1, 3]],

        [[2, 2, 4],
         [3, 3, 2]]]])

In [101]:
arr.reshape(1,2,2,3).ndim

4

In [102]:
arr.reshape(4,3,1) # 3 rows 1 column repeated 4 times in the third dimension

array([[[3],
        [3],
        [1]],

       [[1],
        [1],
        [3]],

       [[2],
        [2],
        [4]],

       [[3],
        [3],
        [2]]])

In [106]:
# conditions on array

arr1 = np.random.randint(1,10,(5,6))

In [107]:
arr1


array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [108]:
arr1.size

30

In [109]:
arr1.shape

(5, 6)

In [110]:
arr1.ndim

2

In [111]:
arr1

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [112]:
arr1 > 3

array([[False,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [False,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False],
       [False,  True, False,  True, False,  True]])

In [113]:
arr1[arr1 > 3] #select all the element of arr1 where the condition is true

array([6, 6, 4, 9, 5, 6, 9, 8, 8, 7, 4, 9, 6, 9, 8, 4, 6, 7, 9, 4, 5])

In [114]:
arr1 [arr1<3]

array([1, 1, 2, 1, 2, 1, 2])

In [115]:
arr1

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [ ]:
# to access elements in an array

In [116]:
arr1[0] # get in first row 

array([3, 6, 1, 1, 6, 4])

In [118]:
arr1[1]

array([9, 5, 6, 9, 8, 8])

In [119]:
arr1[1][2] # in this second row third element

6

In [120]:
arr1

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [121]:
arr1[3][1]

8

In [122]:
arr1

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [124]:
# from oth row to 2nd row

arr1[0:3]

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6]])

In [126]:
# 0 to 2nd row and 0th and 2nd column

arr1[0:3,[0,2]]

array([[3, 1],
       [9, 6],
       [2, 4]])

In [127]:
# slicing on both rows and columns together

arr1

array([[3, 6, 1, 1, 6, 4],
       [9, 5, 6, 9, 8, 8],
       [2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [128]:
arr1[0:3,1:3]

array([[6, 1],
       [5, 6],
       [7, 4]])

In [129]:
arr1[0:3,1:4]

array([[6, 1, 1],
       [5, 6, 9],
       [7, 4, 9]])

In [130]:
arr1[0:3,[0,1]]

array([[3, 6],
       [9, 5],
       [2, 7]])

In [132]:
arr1[0,[1,3]]

array([6, 1])

In [134]:
arr1[2:4,[0,3]] # comma is to particular column

array([[2, 9],
       [9, 6]])

In [136]:
arr1[2:5]

array([[2, 7, 4, 9, 3, 6],
       [9, 8, 4, 6, 7, 1],
       [2, 9, 1, 4, 2, 5]])

In [137]:
arr1[2:5,0:2] # in second slicing is 0:2 output 0 to 1

array([[2, 7],
       [9, 8],
       [2, 9]])

In [141]:
# Mathematical operations on two arrays
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [142]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [143]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [144]:
arr1 + arr2 # indexwise element addition

array([[2, 3, 2],
       [3, 3, 3],
       [3, 2, 4]])

In [145]:
arr1 - arr2

array([[ 0,  1,  0],
       [ 1, -1,  1],
       [ 1,  0,  0]])

In [146]:
arr1,arr2

(array([[1, 2, 1],
        [2, 1, 2],
        [2, 1, 2]]),
 array([[1, 1, 1],
        [1, 2, 1],
        [1, 1, 2]]))

In [147]:
arr1/arr2    # index wise divison

array([[1. , 2. , 1. ],
       [2. , 0.5, 2. ],
       [2. , 1. , 1. ]])

In [148]:
arr1/0

C:\Users\Pratap sarvaiya\AppData\Local\Temp\ipykernel_1856\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
# matrix multiplication >> matrix is a specialised 2-d array
# matrix multiplication is different from index wise multiplication

In [149]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [150]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [151]:
arr1@arr2  # matrix multiplication

array([[4, 6, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [152]:
arr1 * arr2  # index wise Multiplication

array([[1, 2, 1],
       [2, 2, 2],
       [2, 1, 4]])

In [153]:
np.dot(arr1,arr2)  # another way of matrix multiplication

array([[4, 6, 5],
       [5, 6, 7],
       [5, 6, 7]])

In [ ]:
# broadcasting : broadcasting is a backend of addition

In [154]:
arr = np.zeros((3,4))

In [155]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [157]:
arr - 5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [158]:
a = np.array([1,2,3,4])

In [159]:
a

array([1, 2, 3, 4])

In [160]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [163]:
a = np.array([[1,2,3,4]])

In [ ]:
# Transpose >> converting rows to column and column to rows

In [164]:
a

array([[1, 2, 3, 4]])

In [165]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [166]:
arr1

array([[1, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [167]:
arr1.T

array([[1, 2, 2],
       [2, 1, 1],
       [1, 2, 2]])