In [2]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [4]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [5]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [6]:
arr1.flatten() # Return a copy of the array collapsed into one dimension.

array([1, 2, 2, 2, 1, 2, 2, 2, 2])

In [8]:
# expand dimension

arr = np.array([1,2,3,4])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.ndim

1

In [12]:
np.expand_dims(arr,axis=0) # increase the dimension by 1 in the provided axis, 0 means rows(x axis), 1 means column wise(y axis) 

array([[1, 2, 3, 4]])

In [13]:
np.expand_dims(arr,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [14]:
np.expand_dims(arr,axis=1).ndim

2

In [16]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.expand_dims(arr,axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
np.expand_dims(arr,axis=0).ndim

3

In [19]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [20]:
np.expand_dims(arr,axis=0).ndim

3

In [21]:
a = np.array([[1],[2],[3]])

In [22]:
a

array([[1],
       [2],
       [3]])

In [23]:
a.ndim

2

In [25]:
# squeezing the dimension by 1 dimension
np.squeeze(a) # Remove axes of length one from `a`.

array([1, 2, 3])

In [26]:
a

array([[1],
       [2],
       [3]])

In [27]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [28]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [29]:
np.repeat(arr1,2)

array([1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
np.repeat(arr1,2,axis=0)

array([[1, 2, 2],
       [1, 2, 2],
       [2, 1, 2],
       [2, 1, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [34]:
np.repeat(arr2,3,axis=0)

array([[1, 2, 2],
       [1, 2, 2],
       [1, 2, 2],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [35]:
np.repeat(arr2,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2, 1, 1, 1]])

In [36]:
a

array([[1],
       [2],
       [3]])

In [37]:
np.roll(a,-1) # shift place

array([[2],
       [3],
       [1]])

In [38]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [40]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])

In [41]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
np.roll(c,-1)

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [43]:
np.roll(c,-2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [44]:
np.roll(c,2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.roll(c,2,axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [46]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [47]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [48]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [49]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [50]:
arr1+arr2

array([[2, 4, 4],
       [4, 2, 4],
       [3, 4, 3]])

In [51]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 1]])

In [52]:
arr1 * arr2

array([[1, 4, 4],
       [4, 1, 4],
       [2, 4, 2]])

In [53]:
arr1 > arr2

array([[False, False, False],
       [False, False, False],
       [ True, False,  True]])

In [54]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [55]:
~arr1

array([[-2, -3, -3],
       [-3, -2, -3],
       [-3, -3, -3]])

In [56]:
# operations on numpy string array

d = np.array(["pw","skills"])

In [57]:
d

array(['pw', 'skills'], dtype='<U6')

In [58]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [59]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
# mathematical function

In [60]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [61]:
np.sin(arr1)

array([[0.84147098, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743]])

In [62]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684]])

In [63]:
np.tan(arr1)

array([[ 1.55740772, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986]])

In [64]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103]])

In [65]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [66]:
np.power(arr1,3)

array([[1, 8, 8],
       [8, 1, 8],
       [8, 8, 8]], dtype=int32)

In [67]:
np.max(arr1)

2

In [68]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [69]:
np.mean(arr1)

1.7777777777777777

In [70]:
np.min(arr1)

1

In [71]:
np.std(arr1)

0.41573970964154905

In [72]:
np.var(arr1)

0.1728395061728395

In [73]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 1]])

In [74]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 1]])

In [75]:
arr1*arr2

array([[1, 4, 4],
       [4, 1, 4],
       [2, 4, 2]])

In [77]:
np.multiply(arr1,arr2)

array([[1, 4, 4],
       [4, 1, 4],
       [2, 4, 2]])

In [78]:
np.mod(arr1,arr2) # return element wise remainder

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356]])

In [80]:
# sorting and searching in numpy array

e = np.array([5,6,1,2])

In [81]:
e

array([5, 6, 1, 2])

In [82]:
np.sort(e)  # Return a sorted copy of an array.

array([1, 2, 5, 6])

In [83]:
f = np.array([5,199,200,6,7,8])
f

array([  5, 199, 200,   6,   7,   8])

In [84]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [85]:
np.searchsorted(f,170) #Find indices where elements should be inserted to maintain order.

6

In [86]:
f = np.array([5,199,200,0,0,0,0,6,7,8])
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [88]:
np.count_nonzero(f)

6

In [90]:
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [91]:
np.where(f>0) #same as above condition

(array([0, 1, 2, 7, 8, 9], dtype=int64),)

In [93]:
np.extract(f>0,f) # same as above condition

array([  5, 199, 200,   6,   7,   8])

In [94]:
f

array([  5, 199, 200,   0,   0,   0,   0,   6,   7,   8])

In [95]:
f.byteswap() #Swap the bytes of the array elements

array([  83886080, -956301312, -939524096,          0,          0,
                0,          0,  100663296,  117440512,  134217728])

In [96]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [98]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# numpy linear algebra(optional)

In [99]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [100]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [1, 2, 1]])

In [101]:
arr1@arr2

array([[ 7,  8,  8],
       [ 6,  9,  8],
       [ 8, 10, 10]])

In [102]:
arr1

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [104]:
np.linalg.det(arr1)

1.9999999999999993

In [105]:
np.linalg.det(arr2)

2.9999999999999996

In [106]:
# in matrix you can not devide by another matrix,you have inverse

np.linalg.inv(arr2)

array([[-1.        ,  0.66666667,  0.66666667],
       [ 0.        , -0.33333333,  0.66666667],
       [ 1.        , -0.        , -1.        ]])

In [107]:
# 7x + 5.3y-3z = 2
# 2x + 3y -2z = 3
# 3x + 5y -3z = 2

a = np.array([[7,5.3,-3],[2,3,-2],[3,5,-3]])
a

array([[ 7.,  2.,  3.],
       [ 2.,  3., -2.],
       [ 3.,  5., -3.]])

In [108]:
b = np.array([16,8,0])

In [109]:
np.linalg.solve(a,b)

array([ 18.4, -24. , -21.6])